name: Publish NPM Packages

on:
  push:
    tags:
      - 'mock-test-kit-v*.*.*'

jobs:
  publish-mock-test-kit-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: |
          cd packages/mock-test-kit-utils
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-mock-test-kit-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: |
          cd packages/mock-test-kit-core
          yarn install
          yarn build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
