on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.REPO_TOKEN }}
          command: manifest
          default-branch: main
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
      - name: Checkout Repository
        if: ${{ !steps.release.outputs.release_created }}
        uses: actions/checkout@v2
        with:
          ref: release-please--branches--main--components--mock-test-kit
          fetch-depth: 0
      - name: Setup Node
        if: ${{ !steps.release.outputs.release_created }}
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
      - name: Create local changes
        id: changes
        if: ${{ !steps.release.outputs.release_created }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          version=$(node -e "console.log(require('./package.json').version);")
          lernaVersion=$(node -e "console.log(require('./lerna.json').version);")
          if [ "$version" != "$lernaVersion" ]; then
            echo ::set-output name=skip::false
            sha=$(git rev-parse HEAD)
            yarn install
            npx lerna version ${version} --no-push --yes
            git status
            git restore --staged yarn.lock
            git reset $sha
          else
            echo "Versions are the same"
            echo ::set-output name=skip::true
          fi
      - name: Commit files
        if: ${{ !steps.release.outputs.release_created && steps.changes.outputs.skip == 'false' }}
        run: |
          git commit --amend --no-edit -a
      - name: Push changes
        if: ${{ !steps.release.outputs.release_created && steps.changes.outputs.skip == 'false' }}
        uses: ad-m/github-push-action@master
        with:
          force: true
          branch: release-please--branches--main--components--mock-test-kit
