on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest
          default-branch: main
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
      - name: Checkout Repository
        if: ${{ !steps.release.outputs.release_created }}
        uses: actions/checkout@v2
        with:
          ref: release-please--branches--main--components--mock-test-kit
          fetch-depth: 0
      - name: Create local changes
        if: ${{ !steps.release.outputs.release_created }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          version=$(node -e "console.log(require('./package.json').version);")
          sha=$(git rev-parse HEAD)
          yarn install
          npx lerna version ${version} --no-push --yes
          git reset $sha
      - name: Commit files
        if: ${{ !steps.release.outputs.release_created }}
        run: |
          git commit --amend --no-edit -a
      - name: Push changes
        if: ${{ !steps.release.outputs.release_created }}
        uses: ad-m/github-push-action@master
        with:
          force: true
          branch: release-please--branches--main--components--mock-test-kit
